#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

spring:
  mandatory_file_encoding: UTF-8
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true

    properties:
      javax:
        persistence:
          validation:
            group:
              pre-persist: ru.ssk.restvoting.util.validation.ValidationGroup$Persist
              pre-update: ru.ssk.restvoting.util.validation.ValidationGroup$Persist

      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
        jpa.compliance.proxy: false

  sql.init.mode: always
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb
    username: sa
    password:

# Jackson Serialization Issue Resolver
  jackson:
    visibility:
      field: none
      setter: none
      getter: any
      is-getter: any
    default-property-inclusion: non_null
    serialization.write-dates-as-timestamps: false


  # https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-cache
  cache:
    jcache:
      config: classpath:cache/ehcache.xml

logging:
  level:
    root: WARN
    ru.ssk.restvotingboot: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
    org.springframework.cache.jcache.JCacheCacheManager: DEBUG

server.servlet:
  context-path: /restvoting
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true